name: Test packages with Vagrant

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  prepare:
    runs-on: macos-12
    env:
      VAGRANT_CWD: ${{ github.workspace }}/hazelcast-packaging/vagrant

    defaults:
      run:
        working-directory: ./hazelcast-packaging

    steps:
      - name: Checkout hazelcast-packaging repo
        uses: actions/checkout@v2.3.2
        with:
          path: 'hazelcast-packaging'

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run Vagrant up to cache machines
        run: vagrant up

      - name: Run Vagrant halt
        run: vagrant halt

  test:
    runs-on: macos-12
    needs: [prepare]

    defaults:
      run:
        working-directory: ./hazelcast-packaging

    strategy:
      fail-fast: false
      matrix:
        hz_distribution: [ 'hazelcast', 'hazelcast-enterprise' ]
        linux_distribution: [ 'fedora', 'ubuntu' ]
    env:
      HZ_DISTRIBUTION: ${{ matrix.hz_distribution }}
      LINUX_DISTRIBUTION: ${{ matrix.linux_distribution }}
      VAGRANT_CWD: ${{ github.workspace }}/hazelcast-packaging/vagrant

    steps:
      - name: Checkout hazelcast-packaging repo
        uses: actions/checkout@v2.3.2
        with:
          path: 'hazelcast-packaging'

      - name: Run Vagrant machine ${{ env.LINUX_DISTRIBUTION}}
        run: vagrant up ${{ env.LINUX_DISTRIBUTION}}

      - name: Run Hazelcast ${{ matrix.hz_distribution }} on ${{ matrix.linux_distribution }}
        run: |
          vagrant ssh ${{ env.LINUX_DISTRIBUTION}} -c \
            'HAZELCAST_CONFIG="~/hz-config.yaml" hz-start > ~/hz.log 2>&1 &'

      - name: Wait for cluster to be up
        run: |
          vagrant ssh ${{ env.LINUX_DISTRIBUTION}} -c '~/check-hazelcast-health.sh'

      - name: check health via script
        run: vagrant ssh ${{ env.LINUX_DISTRIBUTION}} -c 'hz-healthcheck'

      - name: stop machine
        run: vagrant halt ${{ env.LINUX_DISTRIBUTION}}


  postTest:
    runs-on: macos-10.15
    needs: [test]

    defaults:
      run:
        working-directory: ./hazelcast-packaging

    steps:
      - name: Destroy Vagrant environments if still running
        run: vagrant destroy