name: Test packages with Vagrant

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  prepare:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        hz_distribution: [ 'hazelcast', 'hazelcast-enterprise' ]
        linux_distribution: [ 'fedora', 'ubuntu' ]
    env:
      HZ_DISTRIBUTION: ${{ matrix.hz_distribution }}
      LINUX_DISTRIBUTION: ${{ matrix.linux_distribution }}

    defaults:
      run:
        working-directory: ./hazelcast-packaging

    steps:
      - name: Checkout hazelcast-packaging repo
        uses: actions/checkout@v2.3.2
        with:
          path: 'hazelcast-packaging'

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run Vagrant up
        run: vagrant up

      - name: install Hazelcast distribution ${{ env.HZ_DISTRIBUTION}} on ${{ env.LINUX_DISTRIBUTION}}
        run: vagrant ssh ${{ env.LINUX_DISTRIBUTION}} -C 'sudo apt update && sudo apt install ${{ env.HZ_DISTRIBUTION}}'

      - name: check health
        run: vagrant ssh ${{ env.LINUX_DISTRIBUTION}} -C 'hz-healthcheck'